from app.schemas.common import ErrorBody, ErrorResponse, MessageResponse, PaginatedResponse
from app.schemas.auth import (
    UserRegister,
    UserLogin,
    TokenResponse,
    RefreshTokenRequest,
    UserResponse,
    AddressCreate,
    AddressUpdate,
    AddressResponse,
)
from app.schemas.catalog import (
    ArtistCreate,
    ArtistUpdate,
    ArtistResponse,
    TrackCreate,
    TrackUpdate,
    TrackResponse,
    AlbumCreate,
    AlbumUpdate,
    AlbumResponse,
    AlbumDetailResponse,
)
from app.schemas.product import ProductCreate, ProductUpdate, ProductResponse
from app.schemas.cart import (
    CartItemAdd,
    CartItemUpdate,
    CartItemResponse,
    CartResponse,
    CartMergeRequest,
)
from app.schemas.checkout import (
    CheckoutRequest,
    PaymentIntentResponse,
    CheckoutSummaryResponse,
    ZeroTotalOrderRequest,
)
CheckoutSummary = CheckoutSummaryResponse
from app.schemas.order import OrderItemResponse, OrderResponse, OrderStatusUpdate
from app.schemas.social_and_promo import (
    WishlistAdd,
    WishlistResponse,
    ReviewCreate,
    ReviewResponse,
    CouponCreate,
    CouponUpdate,
    CouponValidateRequest,
    CouponValidateResponse,
    CouponResponse,
    StockNotificationCreate,
    StockNotificationResponse,
)
from app.schemas.admin import AdminSyncRequest, AdminSyncResponse, AdminMetricsResponse

__all__ = [
    "ErrorBody",
    "ErrorResponse",
    "MessageResponse",
    "PaginatedResponse",
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "RefreshTokenRequest",
    "UserResponse",
    "AddressCreate",
    "AddressUpdate",
    "AddressResponse",
    "ArtistCreate",
    "ArtistUpdate",
    "ArtistResponse",
    "TrackCreate",
    "TrackUpdate",
    "TrackResponse",
    "AlbumCreate",
    "AlbumUpdate",
    "AlbumResponse",
    "AlbumDetailResponse",
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "CartItemAdd",
    "CartItemUpdate",
    "CartItemResponse",
    "CartResponse",
    "CartMergeRequest",
    "CheckoutRequest",
    "PaymentIntentResponse",
    "CheckoutSummary",
    "OrderItemResponse",
    "OrderResponse",
    "OrderStatusUpdate",
    "WishlistAdd",
    "WishlistResponse",
    "ReviewCreate",
    "ReviewResponse",
    "CouponCreate",
    "CouponUpdate",
    "CouponValidateRequest",
    "CouponValidateResponse",
    "CouponResponse",
    "StockNotificationCreate",
    "StockNotificationResponse",
    "AdminSyncRequest",
    "AdminSyncResponse",
    "AdminMetricsResponse",
]
